// Generated by npm run build on Fri Nov 20 2020 13:25:37 GMT-0800 (Pacific Standard Time)

import { mergeResolvers } from '@graphql-tools/merge'

import * as rsPVHXibxk from './graphql/hello/hello.js'

export const resolvers = mergeResolvers([rsPVHXibxk])

export const typeDefs = `
type Query {
  hello(name: String = "World"): String
}

schema {
  query: Query
}
`
