// Generated by npm run build on Thu Nov 19 2020 16:43:19 GMT-0800 (Pacific Standard Time)

import { mergeResolvers } from '@graphql-tools/merge'

import * as vzVcjOagLQ from './src/hello.js'

export const resolvers = mergeResolvers([vzVcjOagLQ])

export const typeDefs = `type Query {
  hello: String
}

schema {
  query: Query
}
`
